# Generated by Django 4.0.3 on 2022-03-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.IntegerField()),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, verbose_name='Área do serviço')),
                ('valorDiaria', models.FloatField(null=True)),
                ('valorHora', models.FloatField(null=True)),
                ('periodo', models.CharField(choices=[('Hora', 'Pagamento por hora'), ('Dia', 'Pagamento por dia')], max_length=4)),
                ('profissional', models.ManyToManyField(to='pages.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='EmpXServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.IntegerField()),
                ('avaliacao', models.IntegerField()),
                ('empresa_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.empresa')),
                ('serv_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.servico')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.endereco'),
        ),
        migrations.CreateModel(
            name='ContratoPessXProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('duracaoHora', models.IntegerField()),
                ('pessoa_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pessoa')),
                ('prof_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoEmpXProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('duracaoHora', models.IntegerField()),
                ('empresa_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.empresa')),
                ('profissional_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoEmpXPess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('duracaoHora', models.IntegerField()),
                ('empresa_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.empresa')),
                ('pessoa_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pessoa')),
            ],
        ),
    ]
